remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: ğŸ’»ğŸ‘¨â€ğŸ’»ğŸ´ó §ó ¢ó ³ó £ó ´ó ¿
show_downloads: false
logo: https://avatars.githubusercontent.com/u/1380305?v=4
description: Senior Software Engineer with a proven track record of designing, developing, and delivering high-quality solutions. I enjoy solving tricky problems and optimising systems through elegant code and creative solutions. With a commitment to learning, I am dedicated to staying up-to-date, for example I'm currently learning Rust.